### ISSUE TITLE
SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by Choi-Jinhong** [4tale/Kidari-backend#27]
### 사용 명령어
디버그 모드에서 `Lanch Program` 실행
### 오류 내용
~~~
null: SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: YES)
    at ConnectionManager.connect (/Users/cherimpark/Desktop/hackathon-jeju/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:118:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {name: 'SequelizeAccessDeniedError', parent: Error: Access denied for user 'root'@'localhos… password: YES)
    at Packet.asError (/User…, original: Error: Access denied for user 'root'@'localho…password: YES)
    at Packet.asError (/User…, stack: 'SequelizeAccessDeniedError: Access denied for…ctions (internal/process/task_queues.js:97:5)', message: 'Access denied for user 'root'@'localhost' (using password: YES)'}
null: SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: YES)
    at ConnectionManager.connect (/Users/cherimpark/Desktop/hackathon-jeju/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:118:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {name: 'SequelizeAccessDeniedError', parent: Error: Access denied for user 'root'@'localhos… password: YES)
    at Packet.asError (/User…, original: Error: Access denied for user 'root'@'localho…password: YES)
    at Packet.asError (/User…, stack: 'SequelizeAccessDeniedError: Access denied for…ctions (internal/process/task_queues.js:97:5)', message: 'Access denied for user 'root'@'localhost' (using password: YES)'}
message: 'Access denied for user 'root'@'localhost' (using password: YES)'
name: 'SequelizeAccessDeniedError'
original: Error: Access denied for user 'root'@'localhost' (using password: YES)\n    at Packet.asError 
~~~
- 디버그 모드로 실행하려고 할 때 해당하는 오류가 발생

**Comment by Choi-Jinhong** [comment]
## Causes
- 해당 로컬의 DB 비밀번호가 .env에 설정된 비밀번호와 일치하지 않음
## Solution
1. 켜져있는 서버 끄기
~~~
sudo /usr/local/mysql/support-files/mysql.server stop
~~~

2. mysql을 터미널로 접속
~~~
cd /usr/local/mysql/bin/
sudo ./mysql
/usr/local/mysql/bin/mysql -uroot
~~~
3. 비밀번호 인증을 생략하고 mysql db 접속
~~~
sudo /usr/local/mysql/bin/mysqld_safe --skip-grant-tables
~~~
4. 다른 terminal에서 mysql 접속
~~~
/usr/local/mysql/bin/mysql -uroot
~~~
5. 계정이 설정되어 있는 Database 접속
~~~
use user;
~~~
6. mysql 버전에 따라 다르게 실행
 - mysql 버전이 5.7 미만일 경우
~~~
mysql> update user set password=password('변경할_비밀번호_입력') where user='root';
~~~
- mysql 버전이 5.7 이상일 경우
~~~
update user set authentication_string=password('변경할_비밀번호_입력') where user='root';
~~~
7. Lanch Program 실행
## Reference
https://gomdoreepooh.github.io/notes/mysql-reset-password
